import requests
from bs4 import BeautifulSoup
from flask import Flask, request

app = Flask(__name__)

@app.route('/', methods=['POST'])
def webhook():
    data = request.get_json()
    if data['message']:
        chat_id = data['message']['chat']['id']
        text = data['message']['text']
        if text == '/start':
            send_message(chat_id, 'Hello! This is a YSEQ bot.')
        else:
            send_message(chat_id, 'Sorry, I didn\'t understand that.')
    return 'ok', 200

def send_message(chat_id, text):
    url = f'https://api.telegram.org/bot{TOKEN}/sendMessage'
    data = {'chat_id': chat_id, 'text': text}
    requests.post(url, json=data)

if __name__ == '__main__':
    app.run()
